source 'https://rubygems.org'

gem 'sinatra'
gem 'tilt', '~> 1.4', '>= 1.4.1'
gem 'padrino', '~> 0.13.0'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'pg'
gem 'bcrypt'
gem 'prawn'
gem 'rmagick'
gem 'aws-sdk'
gem 'dotenv'
gem 'bitly'
gem 'mail'

gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-rvm'
gem 'capistrano-passenger'
gem 'capistrano-env-config'

group :development, :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-sinatra'
  gem 'database_cleaner'
  gem 'dm-rspec'
  gem 'launchy'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rspec'
end
